package Modelo.EquipoDAO;
// Generated 22-nov-2019 16:11:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Equipo generated by hbm2java
 */
public class Equipo  implements java.io.Serializable {


     private Integer idEquipo;
     private String nombre;
     private String ciudad;
     private String web;
     private Integer puntos;
     private Set partidosForVisitante = new HashSet(0);
     private Set jugadors = new HashSet(0);
     private Set partidosForLocal = new HashSet(0);

    public Equipo() {
    }

	
    public Equipo(String nombre, String ciudad) {
        this.nombre = nombre;
        this.ciudad = ciudad;
    }
    public Equipo(String nombre, String ciudad, String web, Integer puntos, Set partidosForVisitante, Set jugadors, Set partidosForLocal) {
       this.nombre = nombre;
       this.ciudad = ciudad;
       this.web = web;
       this.puntos = puntos;
       this.partidosForVisitante = partidosForVisitante;
       this.jugadors = jugadors;
       this.partidosForLocal = partidosForLocal;
    }
   
    public Integer getIdEquipo() {
        return this.idEquipo;
    }
    
    public void setIdEquipo(Integer idEquipo) {
        this.idEquipo = idEquipo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getWeb() {
        return this.web;
    }
    
    public void setWeb(String web) {
        this.web = web;
    }
    public Integer getPuntos() {
        return this.puntos;
    }
    
    public void setPuntos(Integer puntos) {
        this.puntos = puntos;
    }
    public Set getPartidosForVisitante() {
        return this.partidosForVisitante;
    }
    
    public void setPartidosForVisitante(Set partidosForVisitante) {
        this.partidosForVisitante = partidosForVisitante;
    }
    public Set getJugadors() {
        return this.jugadors;
    }
    
    public void setJugadors(Set jugadors) {
        this.jugadors = jugadors;
    }
    public Set getPartidosForLocal() {
        return this.partidosForLocal;
    }
    
    public void setPartidosForLocal(Set partidosForLocal) {
        this.partidosForLocal = partidosForLocal;
    }

    @Override
    public String toString() {
        return "Equipo{" + "idEquipo=" + idEquipo + ", nombre=" + nombre + ", ciudad=" + ciudad + ", web=" + web + ", puntos=" + puntos + ", partidosForVisitante=" + partidosForVisitante + ", jugadors=" + jugadors + ", partidosForLocal=" + partidosForLocal + '}';
    }




}


