package Modelo.PartidoDAO;
// Generated 22-nov-2019 16:11:44 by Hibernate Tools 4.3.1


import Modelo.EquipoDAO.Equipo;
import java.util.Date;

/**
 * Partido generated by hbm2java
 */
public class Partido  implements java.io.Serializable {


     private Integer idPartido;
     private Equipo equipoByVisitante;
     private Equipo equipoByLocal;
     private String resultado;
     private Date fecha;
     private String arbitro;

    public Partido() {
    }

	
    public Partido(Equipo equipoByVisitante, Equipo equipoByLocal) {
        this.equipoByVisitante = equipoByVisitante;
        this.equipoByLocal = equipoByLocal;
    }
    public Partido(Equipo equipoByVisitante, Equipo equipoByLocal, String resultado, Date fecha, String arbitro) {
       this.equipoByVisitante = equipoByVisitante;
       this.equipoByLocal = equipoByLocal;
       this.resultado = resultado;
       this.fecha = fecha;
       this.arbitro = arbitro;
    }
   
    public Integer getIdPartido() {
        return this.idPartido;
    }
    
    public void setIdPartido(Integer idPartido) {
        this.idPartido = idPartido;
    }
    public Equipo getEquipoByVisitante() {
        return this.equipoByVisitante;
    }
    
    public void setEquipoByVisitante(Equipo equipoByVisitante) {
        this.equipoByVisitante = equipoByVisitante;
    }
    public Equipo getEquipoByLocal() {
        return this.equipoByLocal;
    }
    
    public void setEquipoByLocal(Equipo equipoByLocal) {
        this.equipoByLocal = equipoByLocal;
    }
    public String getResultado() {
        return this.resultado;
    }
    
    public void setResultado(String resultado) {
        this.resultado = resultado;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getArbitro() {
        return this.arbitro;
    }
    
    public void setArbitro(String arbitro) {
        this.arbitro = arbitro;
    }




}


