package Modelo.JugadorDAO;
// Generated 22-nov-2019 16:11:44 by Hibernate Tools 4.3.1


import Modelo.EquipoDAO.Equipo;
import java.math.BigDecimal;
import java.util.Date;
import org.hibernate.Hibernate;
import org.hibernate.annotations.Proxy;

/**
 * Jugador generated by hbm2java
 */
public class Jugador  implements java.io.Serializable {


     private Integer idJugador;
     private Equipo equipo;
     private String nombre;
     private String apellido;
     private String posicion;
     private Integer idCapitan;
     private Date fechaAlta;
     private Integer salario;
     private BigDecimal altura;

    public Jugador() {
    }

    public Jugador(Equipo equipo, String nombre, String apellido, String posicion, Integer idCapitan, Date fechaAlta, Integer salario, BigDecimal altura) {
       this.equipo = equipo;
       this.nombre = nombre;
       this.apellido = apellido;
       this.posicion = posicion;
       this.idCapitan = idCapitan;
       this.fechaAlta = fechaAlta;
       this.salario = salario;
       this.altura = altura;
    }
   
    public Integer getIdJugador() {
        return this.idJugador;
    }
    
    public void setIdJugador(Integer idJugador) {
        this.idJugador = idJugador;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getPosicion() {
        return this.posicion;
    }
    
    public void setPosicion(String posicion) {
        this.posicion = posicion;
    }
    public Integer getIdCapitan() {
        return this.idCapitan;
    }
    
    public void setIdCapitan(Integer idCapitan) {
        this.idCapitan = idCapitan;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public Integer getSalario() {
        return this.salario;
    }
    
    public void setSalario(Integer salario) {
        this.salario = salario;
    }
    public BigDecimal getAltura() {
        return this.altura;
    }
    
    public void setAltura(BigDecimal altura) {
        this.altura = altura;
    }

    @Override
    public String toString() {
        
        return "Jugador{" + "idJugador=" + idJugador + ", equipo=" + equipo.getNombre() + ", nombre=" + nombre + ", apellido=" + apellido + ", posicion=" + posicion + ", idCapitan=" + idCapitan + ", fechaAlta=" + fechaAlta + ", salario=" + salario + ", altura=" + altura + '}';
    }

    
    



}
//Hibernate.inicialice

